### ISSUE TITLE
/data bind mount works for sonarr but not radarr

### ISSUE THREAD

**Issue by consolecwby** [AdrienPoupa/docker-compose-nas#10]
So i am able to setup sonarr just fine but with radarr when i follow the steps to set /data as the root directory it is blank. If i bin/bash into the container and cd then ls it all shows up. Do i have an issue with permissions? I have matched the file structure as stated in the readme.

**Comment by consolecwby** [comment]
![image](https://user-images.githubusercontent.com/26488453/232139930-7df7df91-566b-4ca2-9d97-9e0e3335c184.png)
here is looking inside the container seems like it works
![image](https://user-images.githubusercontent.com/26488453/232140059-83350151-5a72-4da5-b4eb-8a22c8f7f607.png)
But here is what i get when i set it up in the GUI. (note that i attempted a work around by calling out the volumes like linuxserver/radarr readme but that causes other issues and i get the same result if i do not do this.)

**Comment by AdrienPoupa** [comment]
Hi, I see you are running this in Synology. I remember having a similar issue until I changed the user ID to my user in `.env`:

```
USER_ID=1026
GROUP_ID=100
```

You can see your user ID in DSM's user management, or running `id` in the terminal.

**Comment by consolecwby** [comment]
That got it created a new user for docker then made that match the env. All system up and running. Thankyou for your help once again.
