### ISSUE TITLE
Struggling to understand Adguard and Traefik

### ISSUE THREAD

**Issue by Balssh** [AdrienPoupa/docker-compose-nas#100]
Hi, I've been reading through this repo for the past days and I struggle to understand exactly how Traefik - Adguard interact (I'm a novice in networking). Getting to the point: for now, I try to run only Adguard and Traefik on my (single node) home server. Previously, I could deploy Adguard alone, set it up so that my router DNS points to Adguard's IP on my homeserver. I want to also add Traefik so I can have nice domain names instead of ip addresses + certs. 

Tried to run the setup presented in this repo with only the adguard + traefik parts, but bricked the network :)

Thanks for any help and sorry if this is spam.

**Comment by AdrienPoupa** [comment]
Hi,

Adguard is a DNS server and does not need Traefik per se. It's just used to reverse proxy access to Adguard so you can have several services sharing the same domain name without using different ports.

This project is really meant to be a *arr stack with a few optional extras such as Adguard. There's probably better solutions to run only those two.

If you wanted to make it work though, you'd only need to keep Traefik, maybe homepage and the services listed in the Adguard Docker compose file: https://github.com/AdrienPoupa/docker-compose-nas/blob/master/adguardhome/docker-compose.yml You would also need to remove all the labels no longer needed.
