### ISSUE TITLE
Qbit won't seed

### ISSUE THREAD

**Issue by rkabrick** [AdrienPoupa/docker-compose-nas#16]
Hey! 

Not sure if this is an issue with this config or if it's a setting with my VPN/Router/etc. that I haven't properly configured. However, I am unable to seed anything post download and I don't want to destroy my ratio on my trackers. 

Is there any setting I need to change on either QBIT itself or perhaps PIA to enable uploading? Do I need to do anything with proxy settings?

Thanks in advance

**Comment by AdrienPoupa** [comment]
Hi, yes this is odd. Some things you may want to check:

- Port Forwarding: in qBittorrent > Options > Connection, the port should be set to PIA's port forward, you can check it is the same as the one in `pia-shared/port.dat` or the one from the VPN's container logs. The UPNP checkbox should remain unticked.
- In qBittorrent > Options > Connection, set the Peer Connection Protocol to TCP
- In qBittorrent > Options > Speed, make sure you have no upload limit set
- In qBittorrent > Options > BitTorrent > Privacy, tick the first 3 checkboxes but untick `Anonymous mode` (can cause issues on some trackers)
- In qBittorrent > Options > Advanced, set the network interface to `wg0`, enable `Reannounce to all trackers when IP or port changed`, `Always announce to all trackers in a tier` and `Always announce to all tiers`. I have `Max concurrent HTTP announces` set to 50.
- In your host, make sure you have no firewall blocking traffic (UFW, IPTable?)
- In your router, make sure you're not filtering torrent traffic or blocking ports used by your setup

Good luck!

**Comment by rkabrick** [comment]
Alright well there is *some* upload traffic with those changes. The port wasn't set correctly for some reason. Only seeing Kbps being uploaded which is odd but I guess it's something
