### ISSUE TITLE
Can't acces jellyfin with the mobile app ?

### ISSUE THREAD

**Issue by TechnameFR** [AdrienPoupa/docker-compose-nas#23]
Hello, I am currently testing your solution and everything is working perfectly. 

But I can't access my jellyfin server from the mobile app, yet the app detects the server but still won't connect to it.

However, the server is local and my phone is on the same network.

On the screenshots you can see that when you click on the selected server it tests all possible solutions but still fails.

![Screenshot_20230528_093316_Jellyfin.jpg](https://github.com/AdrienPoupa/docker-compose-nas/assets/92084264/a695e976-ab31-446a-a6ff-8bf9546bcc8b)

![Screenshot_20230528_093324_Jellyfin.jpg](https://github.com/AdrienPoupa/docker-compose-nas/assets/92084264/f0e7bc12-9ae1-421f-a3c1-5ea9773a109a)

**Comment by AdrienPoupa** [comment]
Hello,

It works fine on my end, I just tried to disconnect, change server, select server, reconnect.

Are you using a self signed certificate maybe? Looks like you need one to connect to the Android app: https://github.com/jellyfin/jellyfin-android/issues/783

Thankfully Let's Encrypt support is provided by Traefik so setting it up should be quick and easy :)
