### ISSUE TITLE
Add Unpackerr to extract archives

### ISSUE THREAD

**Issue by AdrienPoupa** [AdrienPoupa/docker-compose-nas#25]
Add [Unpackerr ](https://github.com/Unpackerr/unpackerr)to handle multi part files in qBittorrent.

**Comment by Schaka** [comment]
Consider avoiding to grab rar'd releases altogether. Rars don't really have a place in p2p, imo.
Unfortunately, some trackers still allow them or occasionally don't catch people uploading them quickly enough.

https://github.com/Schaka/rarrnomore

**Comment by AdrienPoupa** [comment]
I started by excluding trackers using archives, but even then on reputable ones some releases end up RAR'ed. Your project would make sense, I will check it out, thanks for the recommendation!
