### ISSUE TITLE
Plex Support

### ISSUE THREAD

**Issue by donferi** [AdrienPoupa/docker-compose-nas#29]
Hey, let me start by saying how great this is!

I wanted to ask if there are plans on adding Plex support. Couldn't find any issue around it so here we are 😅.

Cheers

**Comment by AdrienPoupa** [comment]
Hi there, I am not planning on adding support for Plex myself given Jellyfin is already present and a drop in replacement. If you wish to replace the Jellyfin container with Plex, feel free to do so on your fork :)
