### ISSUE TITLE
qbittorrent healthcheck fails with error 403

### ISSUE THREAD

**Issue by syss** [AdrienPoupa/docker-compose-nas#34]
The healthcheck for qbittorrent is defined as
`test: [ "CMD", "curl", "--fail", "http://127.0.0.1:8080/api/v2/app/version" ]`

When I execute that command it fails with error 403. 
The healthcheck succeeds if I only check for `/`

```
# docker compose exec -it qbittorrent curl --fail "http://127.0.0.1:8080/api/v2/app/version"                         
curl: (22) The requested URL returned error: 403                           
# docker compose exec -it qbittorrent curl --fail "http://127.0.0.1:8080/"                                               
<!DOCTYPE html> 
...
```

Not very familiar with qbt, maybe it makes sense to use another check.

**Comment by syss** [comment]
nevermind found that option in qbt
Settings > Web UI > Authenication >  Bypass authentication for clients on localhost

**Comment by AdrienPoupa** [comment]
It is specified in the readme :)

https://github.com/AdrienPoupa/docker-compose-nas?tab=readme-ov-file#qbittorrent

> Please enable Bypass authentication for clients on localhost as well to make qBittorrent's healthcheck work as well.
