### ISSUE TITLE
Client-side exception on accessing qBittorrent

### ISSUE THREAD

**Issue by bpahunt** [AdrienPoupa/docker-compose-nas#35]
I am unable to access the qBittorrent web UI and receive the below error.

Application error: a client-side exception has occurred (see the browser console for more information).

This seems to be the case regardless of whether I access via the VPN or not (tested by commenting out network_mode: "service:vpn" in the docker-compose.yaml). qBittorrent logs return the below.

(N) 2023-10-29T14:00:50 - Using built-in Web UI.
(W) 2023-10-29T14:00:50 - Couldn't load Web UI translation for selected locale (C).

This indicates an error with no locale being set but I am unable to set one without UI access.

**Comment by bpahunt** [comment]
Forcing the locale does not resolve the problem and logs now show as successfully loaded. Error remains the same when trying to access the web UI.

(N) 2023-10-29T18:13:33 - Web UI translation for selected locale (en) has been successfully loaded.

![image](https://github.com/AdrienPoupa/docker-compose-nas/assets/149238821/c64ae5ae-0a1d-4dd7-8453-b3c785f8a146)

**Comment by eBrewer** [comment]
The issue for me was the health check in the docker-compose.yml file. I made the below change to the health check section. Trying to access the app/version address returned a forbidden error. That's probably not the best health check but it fixed the issue for me.

New test line: test: [ "CMD", "curl", "--fail", "http://127.0.0.1:8080" ]
Old test line: test: [ "CMD", "curl", "--fail", "http://127.0.0.1:8080/api/v2/app/version" ]`

`docker container exec qbittorrent wget http://127.0.0.1:8080/api/v2/app/version
Connecting to 127.0.0.1:8080 (127.0.0.1:8080)
wget: server returned error: HTTP/1.1 403 Forbidden`

**Comment by rayoplateado** [comment]
I had a similar problem. I do exactly what you did and now I can access to WebUI without problems. Thanks for this.

**Comment by bpahunt** [comment]
Thank you eBrewer, this also sorted the issue for me.

**Comment by AdrienPoupa** [comment]
Wow, thanks for tracking this down. I did not realize not activating this would result in a UI crash. I changed the healthcheck endpoint to make it work again.
