### ISSUE TITLE
[Synology] Issue with Qbittorrent container

### ISSUE THREAD

**Issue by consolecwby** [AdrienPoupa/docker-compose-nas#4]
Deploying on Synology DS918+
I disabled the DSM usage of port 80 and 443 to allow using this following these directions.
`sed -i -e 's/80/81/' -e 's/443/444/' /usr/syno/share/nginx/server.mustache /usr/syno/share/nginx/DSM.mustache /usr/syno/share/nginx/WWWService.mustache`
then running 
`synosystemctl restart nginx`

I then followed your quick start instructions on the readme

what ends up happeing is the vpn fires up , *arrs run and jellyfin runs but the qbittorrent does not seem to work and does not end up in the new docker network

when going to host/qbittorrent on the browser it just times out

**Comment by consolecwby** [comment]
here is the traefik log

root@HouseNetServer:/volume1/docker/docker-compose-nas# docker logs traefik
time="2023-02-24T21:24:32Z" level=info msg="Configuration loaded from flags."
time="2023-02-24T21:24:39Z" level=error msg="Unable to obtain ACME certificate for domains \"192.168.1.2\": cannot get ACME client acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:rateLimited :: Error creating new account :: too many registrations for this IP: see https://letsencrypt.org/docs/too-many-registrations-for-this-ip/" routerName=qbittorrent@docker rule="(Host(`192.168.1.2`) && PathPrefix(`/qbittorrent`) || PathPrefix(`/qbittorrent`))" ACME CA="https://acme-v02.api.letsencrypt.org/directory" providerName=myresolver.acme
time="2023-02-24T21:24:47Z" level=error msg="Unable to obtain ACME certificate for domains \"192.168.1.2\": cannot get ACME client acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:rateLimited :: Error creating new account :: too many registrations for this IP: see https://letsencrypt.org/docs/too-many-registrations-for-this-ip/" rule="(Host(`192.168.1.2`) && PathPrefix(`/sonarr`) || PathPrefix(`/sonarr`))" ACME CA="https://acme-v02.api.letsencrypt.org/directory" providerName=myresolver.acme routerName=sonarr@docker
time="2023-02-24T21:24:58Z" level=error msg="Unable to obtain ACME certificate for domains \"192.168.1.2\": cannot get ACME client acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:rateLimited :: Error creating new account :: too many registrations for this IP: see https://letsencrypt.org/docs/too-many-registrations-for-this-ip/" ACME CA="https://acme-v02.api.letsencrypt.org/directory" providerName=myresolver.acme rule="(Host(`192.168.1.2`) && PathPrefix(`/jellyfin`) || PathPrefix(`/jellyfin`))" routerName=jellyfin@docker
time="2023-02-24T21:25:20Z" level=error msg="Unable to obtain ACME certificate for domains \"192.168.1.2\": cannot get ACME client acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:rateLimited :: Error creating new account :: too many registrations for this IP: see https://letsencrypt.org/docs/too-many-registrations-for-this-ip/" rule="(Host(`192.168.1.2`) && PathPrefix(`/radarr`) || PathPrefix(`/radarr`))" ACME CA="https://acme-v02.api.letsencrypt.org/directory" providerName=myresolver.acme routerName=radarr@docker

here is the vpn logs

root@HouseNetServer:/volume1/docker/docker-compose-nas# docker logs vpn
Fetching next-gen PIA server list
Verified OK
Verified server list
Registering public key with PIA endpoint; id: nl_amsterdam, cn: amsterdam416, ip: 212.102.35.150
Generating /etc/wireguard/wg0.conf
Using PIA DNS servers: 10.0.0.243,10.0.0.242
Port forwarding is available at this location
Successfully generated /etc/wireguard/wg0.conf
Fri Feb 24 21:24:36 UTC 2023: Bringing up WireGuard interface wg0
ERROR: (wg0) 2023/02/24 21:24:37 Failed to create TUN device: CreateTUN("wg0") failed; /dev/net/tun does not exist
Fri Feb 24 21:24:37 UTC 2023: Fatal error
[#] ip link add wg0 type wireguard
RTNETLINK answers: Not supported
[!] Missing WireGuard kernel module. Falling back to slow userspace implementation.
[#] wireguard-go wg0
┌──────────────────────────────────────────────────────┐
│                                                      │
│   Running wireguard-go is not required because this  │
│   kernel has first class support for WireGuard. For  │
│   information on installing the kernel module,       │
│   please visit:                                      │
│         https://www.wireguard.com/install/           │
│                                                      │
└──────────────────────────────────────────────────────┘
Unable to access interface: Protocol not supported
[#] ip link delete dev wg0
Cannot find device "wg0"
root@HouseNetServer:/volume1/docker/docker-compose-nas#

**Comment by AdrienPoupa** [comment]
Hello! Yes, it seems like you are missing Wireguard. I had to install this first to make it work, given DSM's kernel does not support Wireguard by default: https://github.com/vegardit/synology-wireguard/releases/tag/WireGuard-1.0.20220627-DSM7.1

I will add this to the README

**Comment by consolecwby** [comment]
Well i tried the WireGuard-apollolake-1.0.20220627_DSM7.1.spk which seems to be the correct package for a DS218+ and installed it using the DSM package center manual installation process. It will install but does not run. when i hit repair it does not work. I do not have the expertise to roll my own package from the source code so i guess i am SOL. Thanks for at least responding to my issue and providing an explanation as to why i have never been able to get wire guard to work on your stack or any other containers.

**Comment by AdrienPoupa** [comment]
According to the main repository README, Wireguard must be started as root from the command line: `sudo /var/packages/WireGuard/scripts/start`, see step 4 here: https://github.com/runfalk/synology-wireguard#installation

**Comment by consolecwby** [comment]
Thats it!!! Thankyou so so much i have been trying to get wiregaurd to work on this damn nas for almost 2 years with no luck. May the holy machine spirit or whatever god you follow bless you.

**Comment by AdrienPoupa** [comment]
I improved the README with a new [Synology section](https://github.com/AdrienPoupa/docker-compose-nas/commit/fc33f28f213670166e45019d11b9a58340e13c70), hopefully it will help newcomers :)
