### ISSUE TITLE
Jellyfin does not work through traefik

### ISSUE THREAD

**Issue by saeubank** [AdrienPoupa/docker-compose-nas#42]
Hi, Thanks for creating this stack it is very helpful.

I am able to get everything to work except Jellyfin through traefik.

When I try to go to myurl.com/jellyfin I get `Application error: a client-side exception has occurred (see the browser console for more information).`

The console doesnt have any useful info and neither does does the traefik and jellyfin logs.

I am able to use all other services just fine.
Also if I expose the 8096 port in docker-compose.yml for Jellyfin I am able to access Jellyfin through 196.0.x.xxx:8096 

I have tried setting up various options from https://jellyfin.org/docs/general/networking/traefik2/ but have had no luck fixing this issue. 

Any ideas?

**Comment by wrapper** [comment]
Have you got Let's Encrypt working? https://github.com/AdrienPoupa/docker-compose-nas/issues/23

**Comment by saeubank** [comment]
I believe so, the acme.json is there and looking at the logs let's encrypt works.
Also all other services work except for Jellyfin.

Jellyfin works fine through the exposed port and through swiftfin

Perhaps it is because I am using a raspberry pi.

I'll close this thread since the raspberry pi is a bit spotty for jellyfin anyways.

I apprecate the help though.

**Comment by saeubank** [comment]
Reopening this issue since I tried this on a fresh install of x86_64 ubuntu 22.04 with the linux kernal 6.5.0-15-generic and am still seeing this issue.

All other services work fine, it is only jellyfin that is having issues (fails to connect and always says starting on homepage).
I am a bit at a loss for what to do.

**Comment by saeubank** [comment]
Oh that did it!
I believe what happened is I ran `update-config.sh` before jellyfin was finished with its initialization so it never updated.
Running it again fixed the issue.

Thank you very much!
