### ISSUE TITLE
Traefik and SSL Certificates Setup Steps

### ISSUE THREAD

**Issue by consolecwby** [AdrienPoupa/docker-compose-nas#5]
So to use the nas with jellyfin clients other than a pc/phone browser i have to setup this SSL certificate i think since the apps reject self signed certificates. I am a little lost on what i need to sign up for and to put in the environment file so that your scripts can do their magic. Could you expand the readme section or point to an instruction.  If using a synology can i use these steps? [https://kb.synology.com/en-uk/DSM/tutorial/How_to_enable_HTTPS_and_create_a_certificate_signing_request_on_your_Synology_NAS]

**Comment by AdrienPoupa** [comment]
Hi!

No, the way the project is setup has nothing to do with Synology and their own Let's Encrypt package.

By default, it assumes you are using CloudFlare to manage the DNS records of your domain.

Then you need to fill your `.env`:

- CLOUDFLARE_EMAIL
- CLOUDFLARE_DNS_API_TOKEN 
- CLOUDFLARE_ZONE_API_TOKEN

More information [here](https://go-acme.github.io/lego/dns/cloudflare/) and [here](https://developers.cloudflare.com/fundamentals/api/get-started/create-token/).

Then, given the hostname is also set in the `.env`, Traefik will automatically run the DNS 01 challenge in CloudFlare and generate valid Let's Encrypt certificates.

**Comment by consolecwby** [comment]
So do I need to purchase a domain name. I was hoping to keep things as local as possible but the Jellyfin client apps require outside certification I guess. I have one from google domains for another project. Do I just use that and have cloud fare manage the dns? I think I can set the name servers what ever that is to cloud fare.

**Comment by AdrienPoupa** [comment]
Yes, you cannot have a valid certificate without a domain name. However, that domain name may point to a private IP, and not resolve outside of your network.

Unfortunately, it looks like Google Domain is not available for DNS01 challenge: https://stackoverflow.com/a/73319748

You may point the your domain's DNS to CloudFlare and handle it from there though.

**Comment by AdrienPoupa** [comment]
It looks like Google Domains was just added! https://go-acme.github.io/lego/dns/googledomains/

**Comment by consolecwby** [comment]
oh nice. still kinda lost but thanks for finding that bit. going to have to
read up on this dns and ssl stuff as i am a bit fuzzy.

**Comment by consolecwby** [comment]
Ok I figured how to rout the google domain to the CloudFlare dns and generated the api tokens to put in the .env file. I deleted and ran compose again the ran the .sh thing. After that do I need to run the Lego dnschallagw somehow? I am not sure where. I tried from the host and inside the trefik container but no joy.

**Comment by AdrienPoupa** [comment]
If you are using CloudFlare as your DNS provider and the credentials were filled in your `.env`, Traefik handles passing the challenge and you don't have to do anything.

**Comment by consolecwby** [comment]
OK i finally got it. I had to delete the acme.json after i commented out the lets encrypt check thing.
