### ISSUE TITLE
Add Bazarr support

### ISSUE THREAD

**Issue by kphilippart** [AdrienPoupa/docker-compose-nas#52]
Hi, 

Is it possible to add a Bazarr support to handle subtitles ? 

I have tried it myself but I can't make it work.

> bazarr:
>     image: lscr.io/linuxserver/bazarr
>     container_name: bazarr
>     environment:
>       - PUID=${USER_ID}
>       - PGID=${GROUP_ID}
>       - TZ=${TIMEZONE}
>     volumes:
>       - ./bazarr:/config
>       - ${DATA_ROOT}:/data
>     restart: always
>     healthcheck:
>       test: [ "CMD", "curl", "--fail", "http://127.0.0.1:6767/bazarr/ping" ]
>       interval: 5s
>       retries: 10
>     labels:
>       - traefik.enable=true
>       - traefik.http.routers.bazarr.rule=(Host(`${HOSTNAME}`) && PathPrefix(`/bazarr`))
>       - traefik.http.routers.bazarr.tls=true
>       - traefik.http.routers.bazarr.tls.certresolver=myresolver
>       - traefik.http.services.sonarr.loadbalancer.server.port=6767
>       - homepage.group=Media
>       - homepage.name=Sonarr
>       - homepage.icon=sonarr.png
>       - homepage.href=/bazarr
>       - homepage.description=Subtitles management
>       - homepage.weight=0
>       - homepage.widget.type=bazarr
>       - homepage.widget.url=http://bazarr:6767/bazarr
> 	 

Bazarr seems up and running but I'm not able to access the web interface. I guess it's a reverse proxy misconfiguration.

`bazarr  | 2024-01-20 20:06:18,448 - root                             (7f94d516ab48) :  INFO (server:67) - BAZARR is started and waiting for request on http://0.0.0.0:6767
`

Thanks in advance

**Comment by AdrienPoupa** [comment]
```
- traefik.http.services.sonarr.loadbalancer.server.port=6767
```
try with this instead:
```
- traefik.http.services.bazarr.loadbalancer.server.port=6767
```

Maybe Bazarr's `config.xml` `<UrlBase>` property will be to be updated too.

**Comment by kphilippart** [comment]
It was a bad copy/paste. Here is my docker-compose.yml
`  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
    volumes:
      - ./bazarr:/config
      - ${DATA_ROOT}:/data
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:6767/bazarr/ping" ]
      interval: 5s
      retries: 10
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr.rule=(Host(`${HOSTNAME}`) && PathPrefix(`/bazarr`))
      - traefik.http.routers.bazarr.tls=true
      - traefik.http.routers.bazarr.tls.certresolver=myresolver
      - traefik.http.services.bazarr.loadbalancer.server.port=6767
      - homepage.group=Media
      - homepage.name=Bazarr
      - homepage.icon=bazarr.png
      - homepage.href=/bazarr
      - homepage.description=Subtitles management
      - homepage.weight=0
      - homepage.widget.type=bazarr
      - homepage.widget.url=http://bazarr:6767/bazarr
`

I changed the base_url with '/bazar' in the ./bazar/config/config.yaml file, but no changes.


`general:
  adaptive_searching: true
  adaptive_searching_delay: 3w
  adaptive_searching_delta: 1w
  anti_captcha_provider: null
  auto_update: true
  base_url: '/bazarr'
`

**Comment by AdrienPoupa** [comment]
I'm glad you got it working! Feel free to open a PR to support it officially :)
