### ISSUE TITLE
Autorenew SSL Cert?

### ISSUE THREAD

**Issue by wrapper** [AdrienPoupa/docker-compose-nas#55]
The steps to generate the first letsencrypt cert were successful, but I am getting an email saying it will expire. What are the steps to renew, and is there any way to automate this?

Thanks

**Comment by AdrienPoupa** [comment]
Hi there, one of the many benefits of using Traefik and [Let's Encrypt's Lego](https://github.com/go-acme/lego) is the automated renewal. When needed, certs will be renewed. If this is not working for you, please check your Traefik logs and you should have more information telling you why it is not working (`docker compose logs traefik`).
