### ISSUE TITLE
Slow Qbit speeds (Doesn't crack 1MBps)

### ISSUE THREAD

**Issue by rkabrick** [AdrienPoupa/docker-compose-nas#58]
I couldn't figure out for the longest time why my qbit container was getting absolute butt cheeks for speed. I used to get 40-50MBps and then a few months ago I started not being able to get above 1 MBps. Finally last night I found a solution. I'm just posting this here in case anyone struggles with the same problem. I thought it was an issue with my vpn provider not supporting port forwarding but after splurging on another vpn service I was still seeing the same issues. 

I won't pretend to understand the internals of the torrent protocol (more specifically `libtorrent`) but reverting QBIT to be the last version where it used `libtorrent` 1.x instead of 2.x resulted in me getting my speeds back. 

Changing the `image` line of this config was the secret sauce: 

```yaml
qbittorrent:
  image: lscr.io/linuxserver/qbittorrent:libtorrentv1-release-4.5.0_v1.2.18-ls7
```

**Comment by AdrienPoupa** [comment]
I'm not sure to understand the issue, the tag we are using ([linuxserver/qbittorrent:libtorrentv1](https://hub.docker.com/r/linuxserver/qbittorrent)) is already using libtorrent v1

**Comment by rkabrick** [comment]
Truly Adrien... My stupidity knows no bounds. At some point I must have switched the qbit container to `latest` without realizing it.

**Comment by AdrienPoupa** [comment]
Makes sense, thanks for the feedback!
