### ISSUE TITLE
add whisparr support / Jdownloader

### ISSUE THREAD

**Issue by gituser823** [AdrienPoupa/docker-compose-nas#59]
hi,

im quite new to docker and will try out your packge, but didnt have the time yet.

Can you please add whisparr optionally to your package?

You can find it here: https://github.com/whisparr/whisparr

Also is it possible to integrate JDownlaoder into the bunch?
Mind, that I did not try your package or any of the Rrr Apps at all yet, so this may already be possible?
Can you tell me how that would work?

Also is it possible to integrate replacing jellyfin optionally with plex?

I will be running the containers on a Synology NAS.

Thanks!

**Comment by AdrienPoupa** [comment]
Hi,

I don't want to add official support for Whisparr, but feel free to do it in your installation.

It seems the arr apps do no support JDownloader, but it's not clear why you'd want to use it. Arr apps usually browse torrent trackers or newsgroups, that are not supported by JDownloader as far as I know.

Also I do not wish to support Plex as Jellyfin is a superior OSS solution in my opinion; once again feel free to make the changes on your own.
