### ISSUE TITLE
Consider using gluetun for VPN

### ISSUE THREAD

**Issue by wrapper** [AdrienPoupa/docker-compose-nas#71]
I'm no expert but this tool could be a solution to allowing for a wider range of VPN providers to be applied per app - https://github.com/qdm12/gluetun

**Comment by AdrienPoupa** [comment]
Hi there,

I really like Gluetun, and would love to use it for the VPN container.

Unfortunately it does not support PIA + Wireguard and Port Forwarding at the moment: https://github.com/qdm12/gluetun/issues/612

When it does, I'll consider switching. In the meantime, you can always override the VPN configuration to use Gluetun: https://github.com/AdrienPoupa/docker-compose-nas/issues/63#issuecomment-1998279552
