### ISSUE TITLE
[feature] Immich breaking versions monitoring

### ISSUE THREAD

**Issue by teaalltr** [AdrienPoupa/docker-compose-nas#72]
Immich is in heavy development. In their release notes they inform people about breaking changes. It would be nice to be able to read that RSS feed and block immich update (which otherwise watchguard would do I guess) if the next version is breaking. Also, maybe have a Telegram bot to notify the user with a link to the changelogs and breaking change notes

**Comment by AdrienPoupa** [comment]
Hello, yes, that's a good idea. However I am not sure how I would go checking whether an update has breaking changes or not, so I think I'll just freeze the version. 

In the upcoming 1.106.0 they will remove the microservices container, I expected changes but maybe not that drastic in such a short amount of time haha.

**Comment by AdrienPoupa** [comment]
Done in https://github.com/AdrienPoupa/docker-compose-nas/pull/77
