### ISSUE TITLE
Make paid VPN subscription optional

### ISSUE THREAD

**Issue by teaalltr** [AdrienPoupa/docker-compose-nas#74]
Yeah because y'know, some people may want a different solution.

It would also be nice if you could optionally plug another subscription like Mozilla VPN or anything at all and still have it working fine.

**Comment by AdrienPoupa** [comment]
This is exactly the example outlined in the documentation: https://github.com/AdrienPoupa/docker-compose-nas?tab=readme-ov-file#customization

As mentioned in #71, I'd like to switch to Gluetun once they are PIA-compatible.

If you have a better solution in mind, please let me know :)

**Comment by teaalltr** [comment]
Yeah missed that one in the docs, sorry. 
Wow gluetun is pretty good, that's ideal, nicely supported and currently being worked on. Hopefully they'll implement Mozilla VPN support too, but otherwise I might go for Mullvad
