### ISSUE TITLE
VPN issues

### ISSUE THREAD

**Issue by antonio-marino** [AdrienPoupa/docker-compose-nas#78]
I've been trying to set this up on a fresh xubuntu 24.04 installation, but I am having some issues integrating the torrent and VPN container.

First run: 

![image](https://github.com/AdrienPoupa/docker-compose-nas/assets/1137049/c7473e69-b0cd-43c6-a640-568f0d43adaa)

Setting up the torrent port settings is timing out:

![image](https://github.com/AdrienPoupa/docker-compose-nas/assets/1137049/eb9760bf-328b-4376-99ba-6697386cba68)

Torrent container is not running yet, shouldn't it be?

![image](https://github.com/AdrienPoupa/docker-compose-nas/assets/1137049/b6eb011c-e239-4fd3-babb-fab9f5835977)

Manually run it:

![image](https://github.com/AdrienPoupa/docker-compose-nas/assets/1137049/4bb5c638-bb9f-4e04-9f86-f3acde2110c9)

Even after manually running it, the VPN is still stuck on the same place. Any ideas what would be the issue?

**Comment by AdrienPoupa** [comment]
Hi, is Wireguard installed in your host machine? `apt install wireguard`

**Comment by antonio-marino** [comment]
It wasn't installed, but I am seeing the same issue after installing it (and creating the containers again from scratch). Any other ideas?

**Comment by AdrienPoupa** [comment]
From your logs it looks like there might be an issue with iptables, but other than that I have no idea. Maybe open an issue upstream? https://github.com/thrnz/docker-wireguard-pia
