### ISSUE TITLE
Jellyfin Bad Gateway

### ISSUE THREAD

**Issue by serkankster** [AdrienPoupa/docker-compose-nas#8]
i encounter a "Bad Gateway" error when I try to open the jellyfin page. Is there any step or config that could be related to this error?

**Comment by AdrienPoupa** [comment]
Hello, it's hard to say without more information. Do you have the output of `docker compose logs jellyfin`?

**Comment by serkankster** [comment]
sharing the output here
https://gist.github.com/serkankster/22d863147a63e3323f307bebb5d8e56b

**Comment by serkankster** [comment]
turns out to be a permissions issue related to some files with wrong PUID permissions. thanks!
