### ISSUE TITLE
Trying to set up radar with qbitorrent

### ISSUE THREAD

**Issue by giorgosn** [AdrienPoupa/docker-compose-nas#80]
I am getting this error
![image](https://github.com/AdrienPoupa/docker-compose-nas/assets/13453884/76a7282a-dc2f-44e5-99cf-fe9594a37d33)

I am not user what to use in host field. Can yotu help me please?

**Comment by AdrienPoupa** [comment]
The hostname should be `vpn`, it is mentioned in the readme: https://github.com/AdrienPoupa/docker-compose-nas?tab=readme-ov-file#download-client
