### ISSUE TITLE
qbittorrent does not download 

### ISSUE THREAD

**Issue by giorgosn** [AdrienPoupa/docker-compose-nas#81]
qbittorrent does not download torrents. I think its something about the network but not sure what.
![image](https://github.com/AdrienPoupa/docker-compose-nas/assets/13453884/48d03bbb-02f5-4a14-8bd1-93ec319987b7)

No errors in the qbittorrent console 
![image](https://github.com/AdrienPoupa/docker-compose-nas/assets/13453884/62d58cdf-bc78-49be-b497-447e6f87d745)

This is the logs of traefik
![image](https://github.com/AdrienPoupa/docker-compose-nas/assets/13453884/7caabfbe-4b1e-4ebe-995e-cd4457d5501d)

**Comment by giorgosn** [comment]
Edit: seems that its a VPN issue. I get this error:
2024-06-28 12:43:17 /scripts/pf_success.sh: line 25: /pia-shared/portupdate-qbittorrent.sh: cannot execute: required file not found

**Comment by giorgosn** [comment]
Solved the error!!
The solution in my problem was that qtorrent did not had rights to the folder that stores the files /data/torrent
`chown -R <user>:<group> /data/torrents` it worked

**Comment by AdrienPoupa** [comment]
Thanks for the followup, I'm glad you could solve it!
