### ISSUE TITLE
Running on localhost 

### ISSUE THREAD

**Issue by jimjoggins** [AdrienPoupa/docker-compose-nas#87]
I've commented out the traefik certificatesresolver lines in docker compose, but I get an error in the traefik container:

`Router uses a non existent certificate resolver`

All the other containers appear to be running ok.

When I access the IP of my server in the browser, I get 404 not found. 

homepage and sonarr etc appear to be serving their sites correctly when I bash into their containers to check, so it seems to be a traefik issue.

I'm running on Ubuntu server 24.04 on a NUC.

**Comment by jimjoggins** [comment]
Got it working locally...

* Comment out / delete all references to `tls` or `myresolver` in `docker-compose.yaml`

* Set `HOSTNAME` in `.env` to local network IP (not `localhost`):
`HOSTNAME=192.168.1.20`

* Restart everything:
`sudo docker ps -aq | sudo xargs docker stop | sudo xargs docker rm`
`sudo docker compose up -d`

* Run update script
`sudo ./update-config.sh`

**Comment by sulazix** [comment]
Can you post your docker-compose.yaml here ?

I edit it twice without success...  I'm probably missing a small thing...

**Comment by jimjoggins** [comment]
@sulazix I've created a fork here:
https://github.com/jimjoggins/docker-compose-nas
The only differences are to `docker-compose.yml` and `.env.example`:
* It's using NordVPN
* I've moved prowlarr and flaresolverr behind the vpn
* I've removed services I'm not using (bazarr and unpackerr)

**Comment by AdrienPoupa** [comment]
You should be able to run it locally by setting `HOSTNAME` to either `localhost`, `127.0.0.1` or your local IP; you may want to set `DNS_CHALLENGE` to false and point to Let's Encrypt staging server instead.
