### ISSUE TITLE
Allow for multiple machines to connect to traefik

### ISSUE THREAD

**Issue by rkabrick** [AdrienPoupa/docker-compose-nas#9]
Hello again! 

Is it possible to run a jellyfin container on one machine (separate from the downloaders) but still have it resolve via `nas.mydomain.com/jellyfin` ?

**Comment by AdrienPoupa** [comment]
Hello, I haven't tried it myself but Traefik is certainly able to do so:

- https://medium.com/@containeroo/traefik-2-0-route-external-services-through-traefik-7bf2d56b1057
- https://blog.ktz.me/traefik-v2-and-external-services-like-home-assistant/

Given the Jellyfin box has a static IP that's reachable from the Traefik host, you should be able to specify that IP as  target.

**Comment by rkabrick** [comment]
Damn that was easy af. Just had to add another record to the cloudflare page and boom! 

Unfortunately, I think I will have to expose two ports with my final config... One for `plex` and another for `notifiarr`. I share plex with family so I'd have to have their Apple TVs & phones added to my tailscale which I don't feel like dealing with 😂... and notifiarr needs to access notifiarr.com. 

Seriously though thank you so much for your work and continued help. I'd love to see you eventually add `recyclarr` to this config to add the TRaSH custom profiles to sonarr & radarr.

**Comment by AdrienPoupa** [comment]
You're welcome! I've been using Tailscale for a while, no ports opened and it works fine so far :)
