### ISSUE TITLE
Homepage fails to start and update-config.sh hangs

### ISSUE THREAD

**Issue by MitchBarnett** [AdrienPoupa/docker-compose-nas#91]
I am pretty new to all this and I'm not sure where I am going wrong.

The only adjustments I have made are in the config adding the sabnzbd compose profile, and appending a compose.override.yml with Nord VPN service to the COMPOSE_FILE.

The first issue I have is that homepage fails to start and keeps restarting
![image](https://github.com/user-attachments/assets/3f747e95-63b7-48ab-8b6e-69ab80c83587)

The logs show the error  `cp: can't stat '/app/config/tpl/*.yaml': No such file or directory`
![image](https://github.com/user-attachments/assets/5e9a10aa-8dbd-4f68-9a0a-ae6c8f1b666d)
I did comment out the line `command: [sh, -c, "cp -n /app/config/tpl/*.yaml /app/config && node server.js"]` which seemed to make it work but I am a noob and don't understand the purpose of this and the consequences of removing it.

The second issue I am struggling with is that ./update-config.sh hangs after the message `container qbittorent Stopped` and has to be terminated, if I try to run it again then it hangs again this time on `Updating sonarr configuration...` and has to be terminated
![image](https://github.com/user-attachments/assets/d9341337-dc5f-47ae-a54a-0a7304a1010e)

I appreciate any help trying to resolve this.

**Comment by AdrienPoupa** [comment]
`cp: can't stat '/app/config/tpl/*.yaml': No such file or directory`: this is very odd, the container is supposed to have those files: https://github.com/AdrienPoupa/docker-compose-nas/tree/master/homepage/tpl thanks to this mount `${CONFIG_ROOT:-.}/homepage:/app/config`

> I did comment out the line command: [sh, -c, "cp -n /app/config/tpl/*.yaml /app/config && node server.js"] which seemed to make it work but I am a noob and don't understand the purpose of this and the consequences of removing it.

This would remove the pre configured layout coming from the templates files; it's alright if you want to use your own.

> The second issue I am struggling with is that ./update-config.sh hangs after the message container qbittorent Stopped and has to be terminated, if I try to run it again then it hangs again this time on Updating sonarr configuration... and has to be terminated

This is odd, but it could be coming from your changes. You don't have to use the script however, you can update your configuration manually:

- Radarr, Sonarr, Lidarr, Prowlarr: 
  - Update each service's `config.yaml` file by setting the `UrlBase` to `/servicename`, eg `/radarr`, etc
  - Update your `.env` file with each service's API key found in the UI or in the config's `*_API_KEY`
- qBittorrent
  - Stop the qBittorrent container
  - Update `/qBittorrent/qBittorrent.conf` by adding
```
WebUI\ServerDomains=*
WebUI\Password_PBKDF2="@ByteArray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"
``

**Comment by MitchBarnett** [comment]
Thanks, for this closing issue as user error is now resolved.
