### ISSUE TITLE
Wireguard PIA - wg0 does not exist

### ISSUE THREAD

**Issue by Keesschilder** [AdrienPoupa/docker-compose-nas#92]
Hi, I'm trying to use your Docker Compose NAS, but I'm having issues with the WireGuard PIA-docker.
I'm getting the following error:

```
vpn  | Fri Oct 18 10:05:38 UTC 2024: Generating auth token
vpn  | Fetching next-gen PIA server list
vpn  | Verified OK
vpn  | Verified server list
vpn  | Registering public key with PIA endpoint; id: ca, cn: montreal435, ip: 91.193.6.142
vpn  | Auth failed
vpn  | {
vpn  |     "status": "ERROR",
vpn  |     "message": "Login failed!"
vpn  | }
vpn  | Fri Oct 18 10:05:39 UTC 2024: Fatal error
vpn  | Fri Oct 18 10:05:57 UTC 2024: Shutting down WireGuard
vpn  | wg-quick: `/etc/wireguard/wg0.conf' does not exist
```

I checked if the file is present in the image itself, but it isn't.
I tried to install WireGuard on the host (Ubuntu 24.04) as well, but without luck.

I did not alter the docker-compose.yml.
The relevant lines in .env are:

```
USER_ID=122
GROUP_ID=984
TIMEZONE="Europe/Amsterdam"
CONFIG_ROOT="."
DATA_ROOT="/storage/data"
DOWNLOAD_ROOT="/storage/data/torrents"
IMMICH_UPLOAD_LOCATION="/storage/data/photos"
PIA_LOCATION=ca
PIA_USER=p***
PIA_PASS=***
PIA_LOCAL_NETWORK="192.168.178.0/16"
HOSTNAME=localhost
```

Have you any idea what I might doing wrong here? All the other containers are running as it should be.

**Comment by AdrienPoupa** [comment]
Make sure Wireguard is installed on your host, then can you try `sudo wg-quick down wg0 && sudo wg-quick up wg0`?

https://stackoverflow.com/a/76922718

**Comment by Keesschilder** [comment]
Sorry for the late response, I was testing several things with Wireguard.
The above mentioned command results in the same error.

I've even reinstalled Ubuntu, installed Docker, installed Wireguard, configured Wireguard as server, opened port in UFW.

But now I'm thinking, should the host be configured as server, as client, or should only installing WireGuard sufficient?

**Comment by Keesschilder** [comment]
I went trough the open and closed issues, and found https://github.com/thrnz/docker-wireguard-pia/issues/57, where the $ or % cannot be handled.
My password was also generated by a password manager with a length >30 characters, including the following symbols:

~
;
?
,
.
@
=
#
\
'
I generated a new password, same length, but without special symbols.
Result: no issue at all, everything is working as it should be!

**Comment by AdrienPoupa** [comment]
I'm glad to hear that, thanks for the update!
