### ISSUE TITLE
Wireguard-PIA container Fatal error

### ISSUE THREAD

**Issue by lucyannofrota** [AdrienPoupa/docker-compose-nas#93]
The PIA Wireguard container is failing when starting

```
vpn  | Fetching next-gen PIA server list
vpn  | Verified OK
vpn  | Verified server list
vpn  | Registering public key with PIA endpoint; id: br, cn: saopaolo404, ip: 188.241.177.182
vpn  | Generating /etc/wireguard/wg0.conf
vpn  | Using PIA DNS servers: 10.0.0.243,10.0.0.242
vpn  | Port forwarding is available at this location
vpn  | Successfully generated /etc/wireguard/wg0.conf
vpn  | Sat Oct 19 12:23:26 UTC 2024: Bringing up WireGuard interface wg0
vpn  | [#] ip link add wg0 type wireguard
vpn  | [#] wg setconf wg0 /dev/fd/63
vpn  | [#] ip -4 address add 10.9.140.170 dev wg0
vpn  | [#] ip link set mtu 1420 up dev wg0
vpn  | [#] resolvconf -a wg0 -m 0 -x
vpn  | could not detect a useable init system
vpn  | [#] wg set wg0 fwmark 51820
vpn  | [#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
vpn  | RTNETLINK answers: File exists
vpn  | [#] resolvconf -d wg0 -f
vpn  | could not detect a useable init system
vpn  | [#] ip link delete dev wg0
vpn  | Sat Oct 19 12:23:27 UTC 2024: Fatal error
```

I don't know if this is a configuration issue, or if it is a problem with the container itself. Do you have any ideas?
Do I need to setup a wireguard server in the host? Or just have the wireguard installed and run the container?

**Comment by AdrienPoupa** [comment]
I'm not sure, but you do need to [install Wireguard](https://www.wireguard.com/install/) in the host first if it's not installed as the container needs it to do syscalls. No need to run the server though.

I don't think it's related to this repo though, could you maybe ask [upstream](https://github.com/thrnz/docker-wireguard-pia)?

**Comment by ssbarnea** [comment]
Any hints on how to disable the VPN feature? Apparently there is no documentation on how to configure it.
