### ISSUE TITLE
How to integrate Immich Public Proxy

### ISSUE THREAD

**Issue by wrapper** [AdrienPoupa/docker-compose-nas#96]
Hey thanks again for your work here. I'm using the immich setup with tailscale but I would also like to use this script: https://github.com/alangrainger/immich-public-proxy

To be able to offer public URLs to otherwise private galleries on immich.

Do you know how I might go about making it work? I understand that I would need to have Traefik serve the requests to the proxy without going through Tailscale, but I'm not sure how to do that.

Thanks

**Comment by AdrienPoupa** [comment]
Hi there, if you want to expose the proxy publicly, I think I would create a [Cloudflare Tunnel](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/) so you don't have to open any port locally or changing Traefik's configuration.
