### ISSUE TITLE
Homepage api errors in browser console - not loading at all. 

### ISSUE THREAD

**Issue by brettswift** [AdrienPoupa/docker-compose-nas#98]
First off - awesome project, thanks.   Added a few things I didn't have on my starr build and I now prefer this one :) 

Running on 22.04 (PopOS). 

On the homepage app, I'm getting a lot of API Errors showing up int he browser console. 
 I can't get even a hard coded `settings.yaml` file to show changes.   

home.domain.com/api/releases,  /api/validate,  /api/bookmarks etc. 

my [fork](https://github.com/brettswift/docker-compose-nas)

Everything else is working great. 

I'm using latest images as of this post,   no logs for homepage in `/app/config/logs` either.  

Is there some extra change required that I've missed ?

**Comment by AdrienPoupa** [comment]
Hello,

It should all be working as expected when configured, the only thing that comes to mind is your `.env` configuration, are all the API keys filled out? Make sure to reload the whole stack with `up -d` after modifying the env file so that Homepage can pick up the changes.

**Comment by brettswift** [comment]
So the strange thing is I have all those keys.  It doesn't load anything on the first time but then when I restart the traefik container I see the config loading.  

Ie the background and sections are there.   Even for a moment I see CPU stats.  

It'll go to "API Error".  Or it will go to API Error as soon as I log into homepage.

**Comment by AdrienPoupa** [comment]
Do you have some Docker logs? `docker compose logs homepage`

**Comment by castrolem** [comment]
Not OP, but this is what I'm getting from the logs after running the containers, the `update-config.sh` file, and looking at my logs

```
docker logs homepage
cp: can't stat '/app/config/tpl/*.yaml': No such file or directory
cp: can't stat '/app/config/tpl/*.yaml': No such file or directory
cp: can't stat '/app/config/tpl/*.yaml': No such file or directory
cp: can't stat '/app/config/tpl/*.yaml': No such file or directory
cp: can't stat '/app/config/tpl/*.yaml': No such file or directory
cp: can't stat '/app/config/tpl/*.yaml': No such file or directory
cp: can't stat '/app/config/tpl/*.yaml': No such file or directory
cp: can't stat '/app/config/tpl/*.yaml': No such file or directory
cp: can't stat '/app/config/tpl/*.yaml': No such file or directory
cp: can't stat '/app/config/tpl/*.yaml': No such file or directory
```

If I do `ls`, I see the homepage folder from the repo with the tpl folder and all the yaml files.

**Comment by brettswift** [comment]
Hey, sorry I didn't have much time recently to test.  I did last night however, and for posterity I'll leave these notes here. 

I think it's a traefik config issue. 

Test scenario: 

1. docker compose down (everything)
2. docker compose up -d homepage
3. docker compose up -d traefik

Now traefik takes 30 seconds (as do they all) to initialize.   In the time period where homepage is up, and traefik is still in "starting" state..   the widgets work. 

Once Traefik goes from "starting" to "healthy",   the widgets stop working.    So there is some configuration there that isn't right. 

I've stripped away the configs and I think it's as close to the default compose file you have.   I guess the question is, what happens when the traefik image finally becomes healthy.  It's that moment when the widgets break..... hmmm

**Comment by brettswift** [comment]
ok this seems to have fixed it: 

```yaml
  traefik:
    # ... other config ...
    labels:
      - traefik.http.routers.homepage.middlewares=homepage-headers,homepage-security,homepage-stripprefix
 
~~~
  homepage:
    # ... other config ...
    labels:
      - traefik.http.middlewares.homepage-preserve.headers.customrequestheaders.X-Forwarded-Prefix=/
```

👍
